hmpps-auth:
  url: "http://localhost:8090/auth"
spring:
  flyway:
    locations: classpath:db/migration/dev

hmpps:
    ai-gateway:
      model:
        prefix: bedrock-dpr-development
  #sqs:
   #queues:
     #domaineventsqueue:
            #queueName: ${HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_QUEUE_NAME}
            #dlqName: ${HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_DLQ_NAME}
