hmpps-auth:
  url: "http://localhost:8090/auth"
spring:
  flyway:
    locations: classpath:db/migration/dev

hmpps:
    sqs:
      enabled: true
      queues:
        jdarequestqueues:
          queuename: ${HMPPS_JDA_REQUEST_QUEUE_NAME}
          dlqName: ${HMPPS_JDA_REQUEST_DLQ_NAME}
        jdaresponsequeues:
          queuename: ${HMPPS_JDA_RESPONSE_QUEUE_NAME}
          dlqName: ${HMPPS_JDA_RESPONSE_DLQ_NAME}
  #sqs:
   #queues:
     #domaineventsqueue:
            #queueName: ${HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_QUEUE_NAME}
            #dlqName: ${HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_DLQ_NAME}
