---
# Per environment values which override defaults in hmpps-justice-data-agent-worker/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: justice-data-agent-worker-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    SPRING_PROFILES_ACTIVE: "dev"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SPRINGDOC_API-DOCS_ENABLED: "true"
    SPRINGDOC_SWAGGER-UI_ENABLED: "true"
  namespace_secrets:
    sqs-jda-request-queue-secret:
      HMPPS_JDA_REQUEST_QUEUE_NAME: "sqs_queue_name"
      HMPPS_JDA_REQUEST_DLQ_NAME: "sqs_dlq_name"
    sqs-jda-response-queue-secret:
      HMPPS_JDA_RESPONSE_QUEUE_NAME: "sqs_queue_name"
      HMPPS_JDA_RESPONSE_DLQ_NAME: "sqs_dlq_name"


  allowlist:
    analytical_platform-prod-1: 54.195.74.96/32
    analytical_platform-prod-2: 79.125.36.56/32
    analytical_platform-prod-3: 63.35.122.32/32

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: information
